#!/usr/bin/env bash
# coord-managed-hook-v1
# Generated by coord install. Local policy lives in the workspace config;
# canonical hook behavior lives in the coordination install (or vendor copy).
set -euo pipefail

hook_name="@HOOK_NAME@"
expected_agent="@AGENT_ID@"
expected_workspace="@WORKSPACE_CONFIG@"
mode="@HOOK_MODE@"

blocked() {
  echo "HOOK BLOCKED: $1" >&2
  echo "  Fix: rerun coord install for agent '$expected_agent' and this product." >&2
  exit 1
}

agent_id="$(git config --local --get consensus.agentId 2>/dev/null || true)"
[[ "$agent_id" == "$expected_agent" ]] || blocked "agent identity is missing, malformed, or does not match this clone."

workspace="$(git config --local --get coord.workspaceConfig 2>/dev/null || true)"
[[ "$workspace" == "$expected_workspace" && -r "$workspace" ]] || blocked "workspace config is missing or does not match the installed workspace."

if [[ "$mode" == "shim" ]]; then
  expected_install_root="@INSTALL_ROOT@"
  install_root="$(git config --local --get coord.installRoot 2>/dev/null || true)"
  [[ "$install_root" == "$expected_install_root" ]] || blocked "coord.installRoot is missing or does not match the installed coordination root."
  [[ -d "$install_root/githooks" ]] || blocked "coordination hook bodies are missing at $install_root/githooks."
  canonical="$install_root/githooks/$hook_name"
else
  canonical="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.coord-vendor/githooks/$hook_name"
fi

[[ -x "$canonical" ]] || blocked "canonical $hook_name hook is missing or not executable."
original="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$hook_name.coord-original"

if [[ "$hook_name" == "pre-push" ]]; then
  input="${TMPDIR:-/tmp}/coord-pre-push.$$.input"
  umask 077
  cat > "$input"
  trap 'rm -f "$input"' EXIT HUP INT TERM
  if [[ -x "$original" ]]; then "$original" "$@" < "$input"; fi
  "$canonical" "$@" < "$input"
  exit $?
fi

if [[ -x "$original" ]]; then "$original" "$@"; fi
exec "$canonical" "$@"
