#!/usr/bin/env bash
# Generated by `coord install` into an AGENT CLONE's .git/hooks/. Never tracked,
# never written into a product's default branch: a human clone of the same
# remote has no coordination hooks at all and is unaffected by coordination.
#
# This file carries no policy. The hook bodies live in the coordination install
# at $installRoot/githooks/, so upgrading coordination upgrades every clone and
# the shim never needs regenerating.
#
# It fails closed on purpose. A missing install root must block loudly; the one
# outcome this design refuses is an agent that keeps committing with every gate
# silently switched off.
set -euo pipefail

hook="$(basename "$0")"
install_root="$(git config --local --get coord.installRoot 2>/dev/null || true)"

if [[ -z "$install_root" ]]; then
  echo "HOOK BLOCKED: coord.installRoot is unset in this clone, so the coordination hook bodies cannot be located." >&2
  echo "  This clone has coordination hooks installed, so it is an agent clone and must not commit ungated." >&2
  echo "  Fix: coord install --product <product> --coord-root <runtime> --agents <agents>" >&2
  echo "  Or remove the wiring entirely: coord uninstall --product <product> --coord-root <runtime>" >&2
  exit 1
fi

body="$install_root/githooks/$hook"

if [[ ! -x "$body" ]]; then
  echo "HOOK BLOCKED: coord.installRoot points at '$install_root', which has no executable githooks/$hook." >&2
  echo "  The coordination install was moved, renamed, or partially built." >&2
  echo "  Fix: coord doctor --coord-root <runtime> --product <product>" >&2
  exit 1
fi

exec "$body" "$@"
