#!/usr/bin/env bash
# Generated by `coord install`. Do not edit.
# Canonical hook bodies live in the coordination install; edit them there.
set -euo pipefail
install_root="$(git config --local --get coord.installRoot 2>/dev/null || true)"
if [[ -z "$install_root" || ! -d "$install_root/githooks" ]]; then
  echo "HOOK BLOCKED: coordination is not installed for this agent clone." >&2
  echo "  Expected install root: ${install_root:-<unset>}" >&2
  echo "  Fix: coord install --product <product> --coord-root <runtime> --agents <ids>" >&2
  exit 1
fi
hook_body="$install_root/githooks/$(basename "$0")"
if [[ ! -x "$hook_body" && ! -f "$hook_body" ]]; then
  echo "HOOK BLOCKED: missing hook body at $hook_body" >&2
  echo "  Re-run coord install, or restore the coordination checkout at $install_root." >&2
  exit 1
fi
exec "$hook_body" "$@"
