#!/usr/bin/env bash
# scripts/lib/launcher.sh — the single source of truth for start-<agent>.sh.
#
# The launcher is generated per clone and never tracked: it carries that clone's
# vendor flags, and setup rewrites it on every run, so a tracked copy guarantees
# a dirty worktree (see docs/launcher-untracking-migration.md).
#
# Two callers generate it, which is exactly why the template lives here rather
# than in either of them:
#
#   src/setupWorkspace.ts     writes it during `coord install`
#   githooks/post-merge       rewrites it when a pull removes it
#
# A second copy of this template drifted from the first within a day of being
# written. Keep both callers on these functions.

# launcher_command <agent>
#
# Emits the shell lines that launch one agent. This is the only place a vendor's
# flags are recorded; setup scripts and the post-merge hook both read them here.
#
# Every vendor below accepts --add-dir for an extra writable root, so the
# completion mailbox is granted with "${coord_grant[@]}" rather than by widening
# the sandbox. That array is computed by the generated launcher at exec time
# (see write_launcher); it is empty when there is no current issue. The
# expansion is written as ${a[@]+"${a[@]}"} because macOS /bin/bash is 3.2,
# where a plain "${a[@]}" on an empty array aborts under `set -u`.
launcher_command() {
  case "$1" in
    claude)
      printf 'exec claude --permission-mode auto ${coord_grant[@]+"${coord_grant[@]}"}\n'
      ;;
    codex)
      # The completion receipt now lives in the mailbox, which is granted
      # explicitly, so workspace-write is enough. danger-full-access was only
      # ever here because `complete` sat under coord-runtime and workspace-write
      # prompted for it — that reason is gone, and the broad grant reached
      # cursors.json and peers' orders along with it.
      printf 'exec codex --ask-for-approval never --sandbox workspace-write ${coord_grant[@]+"${coord_grant[@]}"}\n'
      ;;
    antigravity)
      # agy installs into ~/.local/bin, which a login shell does not always
      # have on PATH; without this the launcher cannot find it.
      #
      # --mode accept-edits sets the execution mode; it does not grant tool
      # permissions, so every out-of-whitelist call became an owner prompt and
      # showed up in analytics as agent wait rather than work (median ~7 min,
      # max ~2.3 h on a product run). --dangerously-skip-permissions is a
      # separate flag, so keep the mode and add the grant. Codex already
      # launches unattended for the same reason.
      #
      # Deliberately NOT given `agy --sandbox`, which its own --help describes as
      # "Run in a sandbox with terminal restrictions enabled". This agent has to
      # run `git push` and the project's declared checks from its terminal; a
      # restriction there would stop it publishing the very commit whose SHA it
      # must then write, which is worse than the write refusal being fixed. It
      # also contradicts --dangerously-skip-permissions on the same line. The
      # add-dir below is therefore advisory for this vendor until the sandbox
      # can be verified against a real agy run that pushes.
      printf 'export PATH="$HOME/.local/bin:$PATH"\nexec agy --mode accept-edits --dangerously-skip-permissions ${coord_grant[@]+"${coord_grant[@]}"}\n'
      ;;
    gemini)
      # No mailbox grant: gemini is not a configured coordination harness and
      # has no completion receipt to write.
      printf 'exec gemini\n'
      ;;
    cursor)
      # --add-dir only means something if the harness is sandboxed: an
      # unsandboxed agent can already write anywhere, so the narrow grant would
      # be decoration. `agent --sandbox` documents the exact choices
      # enabled|disabled, so state it rather than relying on the vendor default.
      printf 'if (( ${#coord_grant[@]} > 0 )); then\n  exec agent --sandbox enabled "${coord_grant[@]}"\nelse\n  exec agent\nfi\n'
      ;;
    *)
      return 1
      ;;
  esac
}

# write_git_wrapper <path> <real_git> <clone>
#
# Writes an executable git wrapper at <clone>/.coord/bin/git to block wasteful
# git commands during automated issues.
write_git_wrapper() {
  local path="$1" real_git="$2" clone="$3"
  cat > "$path" <<EOF
#!/usr/bin/env bash
# Generated by \`coord install\`; never tracked. See scripts/lib/launcher.sh.
set -uo pipefail
REAL_GIT="$real_git"
COORD_CLONE="$clone"

[[ -x "\$REAL_GIT" ]] || { echo "coord: \$REAL_GIT is gone; re-run coord install." >&2; exit 127; }
[[ "\${COORD_GIT_DELEGATE:-}" == 1 ]] && exec "\$REAL_GIT" "\$@"
[[ "\${COORD_ISSUE:-}" =~ ^[1-9][0-9]*\$ ]] || exec env COORD_GIT_DELEGATE=1 "\$REAL_GIT" "\$@"

# Skip leading global options to find the subcommand. Any option or environment
# variable that redirects the repository means this is not a read of the clone
# coordination owns, so it passes through untouched.
args=("\$@"); sub=""; i=0
while (( i < \${#args[@]} )); do
  case "\${args[\$i]}" in
    -C|--git-dir|--git-dir=*|--work-tree|--work-tree=*|--namespace|--namespace=*)
      exec env COORD_GIT_DELEGATE=1 "\$REAL_GIT" "\$@" ;;
    -c) i=\$(( i + 2 )) ;;
    -*) i=\$(( i + 1 )) ;;
    *)  sub="\${args[\$i]}"; break ;;
  esac
done
[[ -n "\${GIT_DIR:-}\${GIT_WORK_TREE:-}" ]] && exec env COORD_GIT_DELEGATE=1 "\$REAL_GIT" "\$@"
case "\$PWD/" in "\$COORD_CLONE"/*) : ;; *) exec env COORD_GIT_DELEGATE=1 "\$REAL_GIT" "\$@" ;; esac

refuse() {
  echo "coord: git \$1 is blocked during automated issue \$COORD_ISSUE." >&2
  echo "  Coordination owns checkout state; read bound peer artifacts from the" >&2
  echo "  paths under '## Bound input files' in your action.md." >&2
  exit 2
}
case "\$sub" in
  status|diff) refuse "\$sub" ;;
  show)
    target="\${args[\$(( i + 1 ))]:-}"
    [[ "\$target" =~ ^[0-9a-f]{40}: ]] || refuse "show"
    ;;
esac
exec env COORD_GIT_DELEGATE=1 "\$REAL_GIT" "\$@"
EOF
  chmod +x "$path"
}

# write_launcher <path> <agent> <label> <shared-branch>
#
# Writes an executable launcher, or returns 1 for an agent with no known launch
# command rather than emitting a truncated script.
#
# The signature stays at four arguments on purpose. The mailbox grant is
# per-issue, and neither caller knows an issue number: `coord install` runs
# before any issue exists, and `githooks/post-merge` has only the clone's
# identity. Baking a drop directory in here would need a fifth argument the hook
# cannot supply, and re-rendering the file at `coord start` would make the
# coordinator write inside agent clones and give the hook a second, disagreeing
# template. So the generated launcher stays path-independent and resolves the
# current drop itself, from the clone-local coord.completesRoot key plus
# COORD_ISSUE, which coordination exports on the tmux session before the harness
# starts.
write_launcher() {
  local path="$1" agent="$2" label="$3" shared="$4" command

  command="$(launcher_command "$agent")" || return 1

  # cd by script location, not by a baked-in absolute path: a clone that moves
  # keeps working, and the file stays free of machine-specific state.
  #
  # The toolchain setup below is conditional on what the clone actually
  # contains. Coordination onboards products in any language; a launcher that
  # demanded .nvmrc and pnpm would fail on a Rust or Go repo for reasons that
  # have nothing to do with the product. Where a repo does pin Node, the pin is
  # honoured and failing to honour it is fatal — starting an agent on a fallback
  # version only defers the failure to its first commit, with a confusing error.
  cat > "$path" <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd "\$(dirname "\${BASH_SOURCE[0]}")"

if [[ -f .nvmrc ]]; then
  export NVM_DIR="\${NVM_DIR:-\$HOME/.nvm}"

  if [[ ! -s "\$NVM_DIR/nvm.sh" ]]; then
    echo "ERROR: this repo pins a Node version in .nvmrc, but nvm was not found at \$NVM_DIR/nvm.sh" >&2
    exit 1
  fi

  . "\$NVM_DIR/nvm.sh"
  nvm use
  echo "Node: \$(node --version)"
fi

# Prefer pnpm via Corepack when this is a pnpm repo.
if [[ -f pnpm-lock.yaml ]] && command -v corepack >/dev/null; then
  corepack enable pnpm >/dev/null 2>&1 || true
  command -v pnpm >/dev/null && echo "pnpm: \$(pnpm --version)"
fi

# Grant this harness two narrow writable directories for an automated issue:
# 1) the completion mailbox drop (Git SHA / response markers)
# 2) this agent's ballot response directory under the issue runtime
# Never grant the issue root, peer directories, or the accepted-response archive.
coord_grant=()
coord_completes_root="\$(git config --local --get coord.completesRoot 2>/dev/null || true)"
coord_workspace_config="\$(git config --local --get coord.workspaceConfig 2>/dev/null || true)"
if [[ -n "\$coord_completes_root" && "\${COORD_ISSUE:-}" =~ ^[1-9][0-9]*\$ ]]; then
  coord_drop="\$coord_completes_root/issue-\$COORD_ISSUE/$agent"
  if [[ -d "\$coord_drop" ]]; then
    coord_grant+=(--add-dir "\$coord_drop")
    echo "Completion mailbox: \$coord_drop"
  else
    echo "WARNING: completion mailbox \$coord_drop does not exist; this harness cannot publish its receipt." >&2
    echo "  Fix: coord doctor, or restart the issue so coord start recreates it." >&2
  fi
elif [[ -z "\$coord_completes_root" ]]; then
  echo "WARNING: coord.completesRoot is unset in this clone; no completion mailbox will be granted." >&2
  echo "  Fix: re-run coord install for this workspace." >&2
fi
# Response dir: derive coord root from coord.workspaceConfig path topology
# (nested: …/workspaces/<project>/config.json → outer coord root; flat: config
# dir is the coord root). Never read a coordRoot field from the JSON.
if [[ -n "\$coord_workspace_config" && -f "\$coord_workspace_config" && "\${COORD_ISSUE:-}" =~ ^[1-9][0-9]*\$ ]]; then
  coord_config_dir="\$(dirname "\$coord_workspace_config")"
  coord_config_parent="\$(dirname "\$coord_config_dir")"
  if [[ "\$(basename "\$coord_config_parent")" == "workspaces" ]]; then
    coord_root="\$(dirname "\$coord_config_parent")"
  else
    coord_root="\$coord_config_dir"
  fi
  coord_responses="\$coord_root/issue-\$COORD_ISSUE/agents/$agent/responses"
  if [[ -d "\$coord_responses" ]]; then
    coord_grant+=(--add-dir "\$coord_responses")
    echo "Ballot responses: \$coord_responses"
  else
    echo "WARNING: response directory \$coord_responses does not exist; ballot response actions cannot write." >&2
    echo "  Fix: coord doctor, or restart the issue so coord start recreates it." >&2
  fi
  coord_inputs="\$coord_root/issue-\$COORD_ISSUE/inputs"
  if [[ -d "\$coord_inputs" ]]; then
    coord_grant+=(--add-dir "\$coord_inputs")
    echo "Materialized inputs: \$coord_inputs"
  fi
  coord_worktrees="\$coord_root/issue-\$COORD_ISSUE/worktrees"
  if [[ -d "\$coord_worktrees" ]]; then
    coord_grant+=(--add-dir "\$coord_worktrees")
    echo "Materialized worktrees: \$coord_worktrees"
  fi
fi

echo "=== $label agent | branches issue-<n>/$agent or $agent/<name> | shared: $shared ==="
echo "Automated issue mode: fetch your coordinator action with:"
echo "  coord next --issue <n>"
echo "(uses this clone's coord.workspaceConfig + consensus.agentId)."
echo "Owner-driven manual mode: wait for the owner's chat task, then work on"
echo "  $agent/<name>"
echo "Do not fabricate coordinator actions or evidence in manual mode."

export PATH="\$(pwd)/.coord/bin:\$PATH"
$command
EOF

  chmod +x "$path"
}
