import { chmodSync, existsSync, mkdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";
import { sha256, sha256OfFile } from "./hash.js";
import { git, gitDir, localConfigGet, localConfigUnset } from "./gitExec.js";
import { containedPath } from "./paths.js";

/**
 * Hook wiring for AGENT CLONES only.
 *
 * Everything here writes into a clone's `.git/hooks/`, which is untracked by
 * construction and is git's default hooks path. Two properties follow, and both
 * are load-bearing:
 *
 *   1. A human clone of the same product remote receives nothing. Coordination
 *      constrains agents and the owner control plane, not the product's other
 *      developers.
 *   2. The wiring's presence is the signal that this clone is an agent clone,
 *      so an unresolvable install root or identity can fail closed here without
 *      ever punishing a human.
 *
 * `core.hooksPath` is deliberately not used: when it points at a directory that
 * does not exist, git runs no hooks and reports nothing, which turns every gate
 * off silently. That is the one failure this project refuses.
 */

export const HOOK_NAMES = ["commit-msg", "post-commit", "post-merge", "pre-commit", "pre-push"] as const;
export type HookName = (typeof HOOK_NAMES)[number];

/** Support files a vendored clone needs beside the bodies, resolved by dirname. */
const VENDOR_LIB_FILES = ["lib/identity.sh", "lib/policy.sh", "lib/launcher.sh"] as const;

/** Everything the installer may ever write into, or delete from, a hooks directory. */
const MANAGED_RELATIVE_PATHS: readonly string[] = [...HOOK_NAMES, ...VENDOR_LIB_FILES];
const managedPaths = new Set(MANAGED_RELATIVE_PATHS);

/**
 * A hook the clone already had is moved aside rather than destroyed, and the
 * shim chains it, so adding coordination's gates never removes the product's.
 */
export const PRESERVED_SUFFIX = ".coord-original";

/**
 * Marker carried by every file coordination writes into a hooks directory.
 *
 * Ownership cannot be decided from the manifest alone: it may be absent, or
 * written by an older schema and therefore unreadable. Without an independent
 * signal an installer treats its own previous shim as a third-party hook,
 * preserves it, and then chains the shim to itself.
 */
const MANAGED_MARKER = "coord-managed-hook";

/**
 * Signatures only coordination writes. The second predates the explicit marker
 * and is kept so a clone installed by an earlier version is still recognised as
 * ours rather than preserved as somebody else's hook.
 */
const OWNERSHIP_SIGNATURES = [MANAGED_MARKER, "Generated by `coord install`"];

const isCoordinationOwned = (content: string): boolean =>
  OWNERSHIP_SIGNATURES.some((signature) => content.includes(signature));

const fileIsCoordinationOwned = (path: string): boolean => {
  try {
    return isCoordinationOwned(readFileSync(path, "utf8"));
  } catch {
    return false;
  }
};

export const MANIFEST_NAME = "coord-hooks.json";

export type HookMode = "shim" | "vendor";

const sha256Schema = z.string().regex(/^[a-f0-9]{64}$/);

/**
 * The manifest lives inside an agent's own clone, so an agent can edit it. It
 * is therefore parsed as untrusted input: its keys may name only managed hook
 * paths, because uninstall deletes what they name. An unrestricted key such as
 * `../../../victim`, paired with that file's digest, made owner-run uninstall
 * delete a file outside the hooks directory.
 */
const hookManifestSchema = z
  .object({
    mode: z.enum(["shim", "vendor"]),
    installRoot: z.string().min(1),
    version: z.string().min(1),
    sourceCommit: z.string().regex(/^[a-f0-9]{40}$/),
    canonicalDigest: sha256Schema,
    writtenAt: z.string().min(1),
    files: z
      .record(z.string(), sha256Schema)
      .refine(
        (files) => Object.keys(files).every((key) => managedPaths.has(key)),
        "manifest may only name managed hook paths"
      ),
    preserved: z.array(z.enum(HOOK_NAMES)).default([])
  })
  .strict();

export type HookManifest = z.infer<typeof hookManifestSchema>;

export type HookSyncInput = {
  clone: string;
  installRoot: string;
  version: string;
  sourceCommit: string;
  canonicalDigest: string;
  mode: HookMode;
  dryRun: boolean;
  now?: string;
};

export type HookSyncOutcome = {
  hooksDir: string;
  written: string[];
  repairedMode: string[];
  preserved: string[];
  unchanged: string[];
  clearedHooksPath: boolean;
};

const hooksDirOf = (clone: string): string => join(gitDir(clone), "hooks");

/** Resolve a managed path inside the hooks directory, or refuse. */
const managedTarget = (hooksDir: string, relative: string): string => {
  if (!managedPaths.has(relative)) {
    throw new Error(`Refusing to touch '${relative}': it is not a managed coordination hook path.`);
  }
  return containedPath(hooksDir, relative);
};

const shimTemplatePath = (installRoot: string): string => join(installRoot, "templates", "hooks", "shim.sh");

const bodyPath = (installRoot: string, name: string): string => join(installRoot, "githooks", name);

const launcherLibraryPath = (installRoot: string): string => join(installRoot, "scripts", "lib", "launcher.sh");

const sourcePathFor = (installRoot: string, relative: string): string =>
  relative === "lib/launcher.sh" ? launcherLibraryPath(installRoot) : bodyPath(installRoot, relative);

const isExecutable = (path: string): boolean => {
  try {
    return (statSync(path).mode & 0o111) !== 0;
  } catch {
    return false;
  }
};

/**
 * Digest of every file that decides what a hook does.
 *
 * Stamping only `HEAD` proved insufficient: an uncommitted edit turning
 * `githooks/pre-commit` into `exit 0` leaves the commit unchanged, so doctor
 * compared a correct shim against a correct commit and reported health while
 * every clone on that install ran the modified body.
 */
export const canonicalSourceDigest = (installRoot: string): string => {
  const sources = [
    ...HOOK_NAMES.map((name) => [`githooks/${name}`, bodyPath(installRoot, name)] as const),
    ["githooks/lib/identity.sh", bodyPath(installRoot, "lib/identity.sh")] as const,
    ["githooks/lib/policy.sh", bodyPath(installRoot, "lib/policy.sh")] as const,
    ["templates/hooks/shim.sh", shimTemplatePath(installRoot)] as const,
    ["scripts/lib/launcher.sh", launcherLibraryPath(installRoot)] as const
  ];
  const canonical = sources
    .map(([id, path]) => `${id}:${sha256OfFile(path)}`)
    .sort()
    .join("\n");
  return sha256(canonical);
};

/** The exact bytes a mode expects in a clone, so drift is a content comparison. */
export const plannedHookContents = (input: Pick<HookSyncInput, "installRoot" | "mode">): Map<string, string> => {
  const planned = new Map<string, string>();
  if (input.mode === "shim") {
    const shim = readFileSync(shimTemplatePath(input.installRoot), "utf8");
    for (const name of HOOK_NAMES) planned.set(name, shim);
    return planned;
  }
  for (const name of HOOK_NAMES) planned.set(name, readFileSync(bodyPath(input.installRoot, name), "utf8"));
  for (const relative of VENDOR_LIB_FILES) {
    planned.set(relative, readFileSync(sourcePathFor(input.installRoot, relative), "utf8"));
  }
  return planned;
};

export const manifestPath = (clone: string): string => join(hooksDirOf(clone), MANIFEST_NAME);

export type ManifestRead =
  | { kind: "absent" }
  | { kind: "invalid"; reason: string }
  | { kind: "ok"; manifest: HookManifest };

export const readHookManifest = (clone: string): ManifestRead => {
  const path = manifestPath(clone);
  if (!existsSync(path)) return { kind: "absent" };
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(path, "utf8")) as unknown;
  } catch (error) {
    return { kind: "invalid", reason: error instanceof Error ? error.message : String(error) };
  }
  const result = hookManifestSchema.safeParse(parsed);
  return result.success ? { kind: "ok", manifest: result.data } : { kind: "invalid", reason: result.error.message };
};

/**
 * Install the hook wiring. `shim` (the default) execs the single canonical body
 * from the coordination install, so an upgrade reaches every clone at once and
 * no copy can drift. `vendor` copies the bodies in, for a clone that must run
 * them without resolving `coord.installRoot`; the manifest stamps the source
 * commit so `coord doctor` can call a stale copy stale.
 */
export const writeCloneHooks = (input: HookSyncInput): HookSyncOutcome => {
  const hooksDir = hooksDirOf(input.clone);
  const planned = plannedHookContents(input);
  const previous = readHookManifest(input.clone);
  const previousManifest = previous.kind === "ok" ? previous.manifest : null;
  const written: string[] = [];
  const repairedMode: string[] = [];
  const unchanged: string[] = [];

  // Drop any recorded preservation whose backup is itself one of our own files.
  // That only arises from an earlier installer mistaking its own previous shim
  // for a third-party hook, and leaving it in place would have the shim chain
  // to a shim — which resolves a body named `<hook>.coord-original` and blocks
  // every commit. Self-healing here beats making the operator clean it up.
  const preserved: HookName[] = [];
  for (const name of previousManifest?.preserved ?? []) {
    const backup = `${join(hooksDir, name)}${PRESERVED_SUFFIX}`;
    // No backup left means the record is stale bookkeeping; a backup that is one
    // of our own files means an earlier installer displaced its own shim.
    if (!existsSync(backup)) continue;
    if (fileIsCoordinationOwned(backup)) {
      if (!input.dryRun) rmSync(backup, { force: true });
      continue;
    }
    preserved.push(name);
  }

  // A clone migrating off the tracked-githooks layout still points core.hooksPath
  // at githooks/, which would shadow everything written below and leave the
  // operator reading hooks that are not the ones git runs.
  const hooksPath = localConfigGet(input.clone, "core.hooksPath");
  const clearedHooksPath = hooksPath !== null;

  for (const [relative, content] of planned) {
    const target = managedTarget(hooksDir, relative);
    const exists = existsSync(target);
    const actual = exists ? readFileSync(target, "utf8") : null;

    // A hook this clone already had — not ours now, not ours before — is moved
    // aside and chained by the shim rather than overwritten. Adding
    // coordination's gates does not authorize deleting the product's own.
    if (
      exists &&
      actual !== content &&
      HOOK_NAMES.includes(relative as HookName) &&
      !isCoordinationOwned(actual as string) &&
      previousManifest?.files[relative] !== sha256(actual as string) &&
      !preserved.includes(relative as HookName)
    ) {
      preserved.push(relative as HookName);
      if (!input.dryRun) renameSync(target, `${target}${PRESERVED_SUFFIX}`);
    }

    if (actual === content) {
      // Bytes alone are not health: git silently ignores a hook without its
      // execute bit, so a lost mode must be repaired rather than classified
      // unchanged.
      if (HOOK_NAMES.includes(relative as HookName) && !isExecutable(target)) {
        repairedMode.push(relative);
        if (!input.dryRun) chmodSync(target, 0o755);
        continue;
      }
      unchanged.push(relative);
      continue;
    }

    written.push(relative);
    if (input.dryRun) continue;
    mkdirSync(join(target, ".."), { recursive: true });
    writeFileSync(target, content, "utf8");
    chmodSync(target, 0o755);
  }

  const files = Object.fromEntries([...planned].map(([relative, content]) => [relative, sha256(content)]));
  const manifest: HookManifest = {
    mode: input.mode,
    installRoot: input.installRoot,
    version: input.version,
    sourceCommit: input.sourceCommit,
    canonicalDigest: input.canonicalDigest,
    // A no-op reinstall must leave managed files byte-identical, so the
    // timestamp is only refreshed when something else about the manifest is.
    writtenAt: input.now ?? new Date().toISOString(),
    files,
    preserved: [...preserved].sort()
  };
  const carryTimestamp =
    previousManifest !== null &&
    JSON.stringify({ ...previousManifest, writtenAt: "" }) === JSON.stringify({ ...manifest, writtenAt: "" });
  if (carryTimestamp) manifest.writtenAt = previousManifest.writtenAt;

  if (!input.dryRun) {
    if (clearedHooksPath) localConfigUnset(input.clone, "core.hooksPath");
    mkdirSync(hooksDir, { recursive: true });
    const rendered = `${JSON.stringify(manifest, null, 2)}\n`;
    const manifestFile = manifestPath(input.clone);
    if (!existsSync(manifestFile) || readFileSync(manifestFile, "utf8") !== rendered) {
      writeFileSync(manifestFile, rendered, "utf8");
    }
  }

  return { hooksDir, written, repairedMode, preserved, unchanged, clearedHooksPath };
};

export type HookRemovalOutcome = { removed: string[]; restored: string[]; kept: string[] };

/**
 * Remove only what this installer wrote, and only while it still matches what
 * the manifest recorded, then put back any hook that was moved aside. A hook an
 * operator edited by hand is left in place and reported: uninstall is not
 * licensed to delete work it did not create.
 */
export const removeCloneHooks = (clone: string, options: { dryRun: boolean }): HookRemovalOutcome => {
  const read = readHookManifest(clone);
  const removed: string[] = [];
  const restored: string[] = [];
  const kept: string[] = [];
  if (read.kind === "absent") return { removed, restored, kept };
  if (read.kind === "invalid") {
    kept.push(`${MANIFEST_NAME} is unreadable or malformed (${read.reason}); nothing was deleted`);
    return { removed, restored, kept };
  }

  const hooksDir = hooksDirOf(clone);
  for (const [relative, digest] of Object.entries(read.manifest.files)) {
    const target = managedTarget(hooksDir, relative);
    if (!existsSync(target)) continue;
    if (sha256OfFile(target) !== digest) {
      kept.push(relative);
      continue;
    }
    removed.push(relative);
    if (!options.dryRun) rmSync(target);
  }

  for (const name of read.manifest.preserved) {
    const target = managedTarget(hooksDir, name);
    const backup = `${target}${PRESERVED_SUFFIX}`;
    if (!existsSync(backup)) continue;
    if (existsSync(target)) {
      kept.push(`${name}: ${PRESERVED_SUFFIX} not restored because a hook still occupies the name`);
      continue;
    }
    restored.push(name);
    if (!options.dryRun) renameSync(backup, target);
  }

  if (!options.dryRun) rmSync(manifestPath(clone), { force: true });
  return { removed, restored, kept };
};

export type HookDrift =
  | { kind: "absent" }
  | { kind: "ok"; mode: HookMode }
  | { kind: "unmanaged" }
  | { kind: "invalid-manifest"; reason: string }
  | { kind: "modified"; files: string[] }
  | { kind: "missing"; files: string[] }
  | { kind: "not-executable"; files: string[] }
  | { kind: "stale-vendor"; recordedCommit: string; installCommit: string }
  | { kind: "install-modified"; recordedDigest: string; actualDigest: string }
  | { kind: "shadowed"; hooksPath: string };

/**
 * Classify one clone's hook wiring for `coord doctor`.
 *
 * The comparison is against the canonical source, not against the manifest's
 * own digests. The manifest sits in the agent's clone, so trusting it let an
 * agent rewrite `pre-commit` to `exit 0`, update the matching digest, and be
 * certified healthy by the tool built to catch exactly that.
 */
export const inspectCloneHooks = (input: {
  clone: string;
  installRoot: string;
  installCommit: string;
  canonicalDigest?: string;
}): HookDrift => {
  const read = readHookManifest(input.clone);
  const hooksDir = hooksDirOf(input.clone);
  if (read.kind === "absent") {
    const anyPresent = HOOK_NAMES.some((name) => existsSync(join(hooksDir, name)));
    return anyPresent ? { kind: "unmanaged" } : { kind: "absent" };
  }
  if (read.kind === "invalid") return { kind: "invalid-manifest", reason: read.reason };
  const manifest = read.manifest;

  const hooksPath = localConfigGet(input.clone, "core.hooksPath");
  if (hooksPath !== null) return { kind: "shadowed", hooksPath };

  let expected: Map<string, string>;
  try {
    expected = plannedHookContents({ installRoot: input.installRoot, mode: manifest.mode });
  } catch {
    // The canonical source is unreadable; the install-root check reports that.
    return { kind: "ok", mode: manifest.mode };
  }

  const missing: string[] = [];
  const modified: string[] = [];
  const notExecutable: string[] = [];
  for (const [relative, content] of expected) {
    const target = join(hooksDir, relative);
    if (!existsSync(target)) {
      missing.push(relative);
      continue;
    }
    if (readFileSync(target, "utf8") !== content) modified.push(relative);
    else if (HOOK_NAMES.includes(relative as HookName) && !isExecutable(target)) notExecutable.push(relative);
  }

  if (missing.length > 0) return { kind: "missing", files: missing.sort() };
  if (modified.length > 0) {
    // Vendored copies legitimately lag the install until the operator refreshes
    // them; that is a different remediation from an edited hook.
    if (manifest.mode === "vendor" && manifest.sourceCommit !== input.installCommit) {
      return { kind: "stale-vendor", recordedCommit: manifest.sourceCommit, installCommit: input.installCommit };
    }
    return { kind: "modified", files: modified.sort() };
  }
  if (notExecutable.length > 0) return { kind: "not-executable", files: notExecutable.sort() };

  if (manifest.mode === "vendor" && manifest.sourceCommit !== input.installCommit) {
    return { kind: "stale-vendor", recordedCommit: manifest.sourceCommit, installCommit: input.installCommit };
  }
  if (input.canonicalDigest !== undefined && manifest.canonicalDigest !== input.canonicalDigest) {
    return { kind: "install-modified", recordedDigest: manifest.canonicalDigest, actualDigest: input.canonicalDigest };
  }
  return { kind: "ok", mode: manifest.mode };
};

/**
 * Copy the canonical hook bodies into a product's tracked tree. Only reachable
 * through `--write-product --vendor`, which an owner asks for explicitly; the
 * default install never touches a tracked file.
 *
 * It refuses rather than overwrites. A product that maintains its own tracked
 * `githooks/<name>` owns that file, and an opt-in flag is not consent to
 * destroy it.
 */
export const vendorIntoProductTree = (input: {
  productRoot: string;
  installRoot: string;
  dryRun: boolean;
}): string[] => {
  const targetDir = join(input.productRoot, "githooks");
  const relatives = [...HOOK_NAMES, ...VENDOR_LIB_FILES];
  const written: string[] = [];
  const conflicts: string[] = [];
  for (const relative of relatives) {
    const source = sourcePathFor(input.installRoot, relative);
    const target = join(targetDir, relative);
    const content = readFileSync(source, "utf8");
    if (!existsSync(target)) {
      written.push(join("githooks", relative));
      continue;
    }
    const actual = readFileSync(target, "utf8");
    if (actual === content) continue;
    conflicts.push(join("githooks", relative));
  }
  if (conflicts.length > 0) {
    throw new Error(
      `Refusing to replace tracked product hooks: ${conflicts.join(", ")}.\n` +
        "  --write-product --vendor is additive; it may not overwrite hooks the product maintains.\n" +
        "  Remove or reconcile them first, or drop --write-product and vendor into the agent clones only."
    );
  }
  if (!input.dryRun) {
    for (const relative of relatives) {
      const target = join(targetDir, relative);
      if (existsSync(target)) continue;
      mkdirSync(join(target, ".."), { recursive: true });
      writeFileSync(target, readFileSync(sourcePathFor(input.installRoot, relative), "utf8"), "utf8");
      chmodSync(target, 0o755);
    }
  }
  return written;
};

/** Resolve the commit a coordination checkout is currently at, for the stamp. */
export const installSourceCommit = (installRoot: string): string => {
  const result = git(installRoot, "rev-parse", "--verify", "HEAD^{commit}");
  if (result.exitCode !== 0) {
    throw new Error(
      `Cannot resolve the coordination install commit at ${installRoot}: ${result.stderr.trim()}. ` +
        "The install root must be a git checkout so the stamp can record what a workspace runs against."
    );
  }
  return result.stdout.trim();
};
